const { execSync } = require("child_process");
const https = require('https');

// Configuration - Using Env Vars for Cloud Compatibility
const NOTION_TOKEN = process.env.NOTION_TOKEN;
const MASTER_DB_ID = process.env.MASTER_DB_ID;
const LIVE_BRIEF_PAGE_ID = process.env.LIVE_BRIEF_PAGE_ID;

if (!NOTION_TOKEN || !MASTER_DB_ID || !LIVE_BRIEF_PAGE_ID) {
    console.error("❌ ERROR: Missing required environment variables.");
    console.error("Please ensure NOTION_TOKEN, MASTER_DB_ID, and LIVE_BRIEF_PAGE_ID are set in GitHub Secrets.");
    process.exit(1);
}

// Debug logging (Safe: only shows partials)
console.log(`[DEBUG] Token Status: ${NOTION_TOKEN ? "OK" : "MISSING"}`);

function notionReq(method, path, data) {
    const cmd = `curl -s -X ${method} "https://api.notion.com/v1${path}" \
        -H "Authorization: Bearer ${NOTION_TOKEN}" \
        -H "Notion-Version: 2022-06-28" \
        -H "Content-Type: application/json" \
        ${data ? `--data '${JSON.stringify(data).replace(/'/g, "'\\''")}'` : ""}`;
    try {
        const output = execSync(cmd).toString();
        const json = JSON.parse(output);
        if (json.object === 'error') {
            console.error(`[ERROR] Notion API Error (${path}):`, json);
        }
        return json;
    } catch (e) {
        console.error(`[ERROR] Request failed: ${e.message}`);
        return null;
    }
}

async function getTopGaps() {
    const data = await notionReq("POST", `/databases/${MASTER_DB_ID}/query`, {
        filter: { property: "Status", select: { equals: "Gap" } },
        sorts: [{ property: "Frequency", direction: "descending" }],
        page_size: 3
    });
    return data?.results.map(r => ({
        id: r.id,
        skill: r.properties.Skill.title[0]?.plain_text || "Unknown",
        freq: r.properties.Frequency.number || 0
    })) || [];
}

// ... (fetchJson and getHighSignalResources remain the same) ...

// Helper to get upcoming Saturday
function getNextSaturday() {
    const d = new Date();
    const day = d.getDay(); // 0 (Sun) - 6 (Sat)
    // If today is Saturday (6), diff is 0 (Target: Today).
    // If today is Wednesday (3), diff is 3 (Target: Saturday).
    // If today is Sunday (0), diff is 6 (Target: Next Saturday).
    const diff = 6 - day;
    d.setDate(d.getDate() + diff);
    return d;
}

async function updateLiveDashboard(gaps, date) {
    console.log("\x1b[33mUpdating Live Intelligence Dashboard in Notion...\x1b[0m");

    // 1. Clear existing blocks
    const children = await notionReq("GET", `/blocks/${LIVE_BRIEF_PAGE_ID}/children`);
    if (children?.results) {
        for (const block of children.results) {
            await notionReq("DELETE", `/blocks/${block.id}`);
        }
    }

    // 2. Append new blocks
    const blocks = [
        {
            type: "heading_1",
            heading_1: {
                rich_text: [{ text: { content: `Weekly Brief: ${date}` } }],
                color: "blue"
            }
        },
        {
            type: "callout",
            callout: {
                rich_text: [{ text: { content: "Strategy for the upcoming Saturday session. This dashboard updates daily." } }],
                icon: { emoji: "🎯" },
                color: "gray_background"
            }
        },
        {
            type: "divider",
            divider: {}
        },
        {
            type: "heading_2",
            heading_2: {
                rich_text: [{ text: { content: "TOP SKILL GAPS (Market Demand)" } }],
                color: "red"
            }
        }
    ];

    gaps.forEach((g, i) => {
        blocks.push({
            type: "bulleted_list_item",
            bulleted_list_item: {
                rich_text: [
                    { text: { content: `${g.skill}`, link: null }, annotations: { bold: true, color: "blue" } },
                    { text: { content: ` (Found in ${g.freq} JDs)` } }
                ]
            }
        });
        g.resources.forEach(r => {
            blocks.push({
                type: "paragraph",
                paragraph: {
                    rich_text: [
                        { text: { content: "   🔗 " } },
                        { text: { content: `${r.title}`, link: { url: r.url } }, annotations: { italic: true } }
                    ],
                    color: "gray"
                }
            });
        });
    });

    blocks.push({
        type: "divider",
        divider: {}
    });

    blocks.push({
        type: "paragraph",
        paragraph: {
            rich_text: [{ text: { content: "Generated by Looming Gap Engine (Cloud Edition)", link: null } }],
            color: "gray"
        }
    });

    await notionReq("PATCH", `/blocks/${LIVE_BRIEF_PAGE_ID}/children`, { children: blocks });
}

async function run() {
    console.log("\x1b[36mGenerating High-Signal Weekly Brief (Cloud Edition)...\x1b[0m");

    // 1. Process Queued Study Skills (Cloud-safe call)
    try {
        execSync(`node ${__dirname}/skill_scheduler.js`, { stdio: 'inherit' });
    } catch (e) {
        console.error("Skill Scheduler failed:", e.message);
    }

    // 2. Fetch Skill Gaps
    let gaps = await getTopGaps();
    const primaryGap = gaps[0]?.skill || "N/A";

    // 3. Fetch Learning Resources for ALL Gaps
    for (let i = 0; i < gaps.length; i++) {
        gaps[i].resources = await getHighSignalResources(gaps[i].skill);
    }

    const learningUrl = gaps[0]?.resources[0]?.url || "https://roadmap.sh";

    // Calculate Date for "Upcoming Saturday"
    const targetDateObj = getNextSaturday();
    const dateStr = targetDateObj.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' });
    const targetISO = targetDateObj.toISOString().split('T')[0];

    // 4. Update Daily Intelligence Log (Archive) - REMOVED per user request
    console.log("\x1b[33mArchiving skipped (Database removed).\x1b[0m");

    // 5. Update Master Skill Tracker
    for (const gap of gaps) {
        if (gap.id && gap.resources?.[0]) {
            await notionReq("PATCH", `/pages/${gap.id}`, {
                properties: { "Deep Dive": { url: gap.resources[0].url } }
            });
        }
    }

    // 6. Push to Live Intelligence Dashboard (New 100% Reliable Delivery)
    await updateLiveDashboard(gaps, dateStr);

    console.log("\x1b[32m\x1b[1mSUCCESS: Cloud Brief synchronized and Live Dashboard updated!\x1b[0m");
}

// Reuse fetchJson and getHighSignalResources from above...
async function fetchJson(url) {
    return new Promise((resolve, reject) => {
        https.get(url, { headers: { 'User-Agent': 'NodeJS/LoomingGapEngine' } }, (res) => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => {
                try { resolve(JSON.parse(data)); } catch (e) { resolve(null); }
            });
        }).on('error', reject);
    });
}

async function getHighSignalResources(skill) {
    if (!skill || skill === "N/A") return [{ title: "Upskilling Roadmap", url: "https://roadmap.sh" }];
    const resources = [];
    const cleanSkill = skill.trim();
    const tag = cleanSkill.toLowerCase().replace(/ /g, '');

    const devToApi = `https://dev.to/api/articles?tag=${encodeURIComponent(tag)}&per_page=1&top=365`;
    try {
        const articles = await fetchJson(devToApi);
        if (articles && articles.length > 0) {
            resources.push({ title: `[Article] ${articles[0].title}`, url: articles[0].url });
        }
    } catch (e) { }

    resources.push({ title: `[Video] ${cleanSkill} Video Tutorials`, url: `https://www.youtube.com/results?search_query=${encodeURIComponent(cleanSkill + " tutorial for developers")}` });
    resources.push({ title: `[Roadmap] ${cleanSkill} Learning Path`, url: `https://roadmap.sh/search?q=${encodeURIComponent(cleanSkill)}` });
    return resources.slice(0, 3);
}

run().catch(console.error);
